// Generated by Copilot
import { Agent, Dispatcher, RetryAgent } from 'undici';
import { StatusCodes } from 'http-status-codes';
import type { Logger } from '../telemetry/logger';
import { NoopLogger } from '../telemetry/noopLogger';

/**
 * Options for configuring the retry behavior in HTTP requests.
 */
interface RetryOptions {
  /**
   * Maximum number of retry attempts.
   * @default 3
   */
  maxRetries?: number;

  /**
   * HTTP status codes that should trigger a retry.
   * @default [500, 502, 503, 504]
   */
  statusCodes?: number[];

  /**
   * Error codes that should trigger a retry.
   * @default ['ECONNRESET', 'ECONNREFUSED', 'ETIMEDOUT', 'ENOTFOUND', 'EAI_AGAIN']
   */
  errorCodes?: string[];
}

/**
 * Options for configuring the HTTP client behavior.
 */
interface HttpClientOptions {
  /**
   * Options for configuring retry behavior.
   */
  retry?: RetryOptions;

  /**
   * Options for the underlying agent.
   */
  agentOptions?: Agent.Options;

  /**
   * Logger instance for client operations.
   * @default new NoopLogger()
   */
  logger?: Logger;
}

/**
 * HTTP status codes that should trigger a retry by default.
 */
const DEFAULT_RETRY_STATUS_CODES = [
  StatusCodes.INTERNAL_SERVER_ERROR,
  StatusCodes.BAD_GATEWAY,
  StatusCodes.SERVICE_UNAVAILABLE,
  StatusCodes.GATEWAY_TIMEOUT,
];

/**
 * Error codes that should trigger a retry by default.
 */
const DEFAULT_RETRY_ERROR_CODES = [
  'ECONNRESET', // Connection reset by peer
  'ECONNREFUSED', // Connection refused
  'ETIMEDOUT', // Connection timeout
  'ENOTFOUND', // DNS lookup failed
  'EAI_AGAIN', // Temporary failure in name resolution
];

/**
 * Maximum retry count by default.
 */
const DEFAULT_MAX_RETRIES = 3;

/**
 * Initial delay for retry in milliseconds.
 */
const INITIAL_RETRY_DELAY_MS = 100;

/**
 * Maximum delay for retry in milliseconds (30 seconds).
 */
const MAX_RETRY_DELAY_MS = 30000;

/**
 * Exponential backoff factor.
 */
const RETRY_BACKOFF_FACTOR = 2;

/**
 * Maximum safe retry count to prevent excessive exponential calculations.
 */
const MAX_SAFE_RETRY_COUNT = 15;

/**
 * Creates a RetryAgent with proper configuration for network resilience.
 */
export function createRetryAgent(options: HttpClientOptions = {}): Dispatcher {
  const logger = options.logger ?? new NoopLogger();
  const agentOptions = options.agentOptions ?? {};
  const retryOptions = options.retry ?? {};

  // Create the base agent
  const baseAgent = new Agent(agentOptions);

  // Create the RetryAgent with proper configuration
  // We need to cast to unknown and then any here to fix the type mismatch
  // between our options and what RetryAgent expects
  const retryAgent = new RetryAgent(baseAgent, {
    maxRetries: retryOptions.maxRetries ?? DEFAULT_MAX_RETRIES,
    statusCodes: retryOptions.statusCodes ?? [...DEFAULT_RETRY_STATUS_CODES],
    errorCodes: retryOptions.errorCodes ?? [...DEFAULT_RETRY_ERROR_CODES],
    retry: (_error: Error | null, context: { state: { retryCount: number }; opts: any }, cb: (err: Error | null, delay: number) => void): void => {
      // Extract retry count from context or default to 0
      const retryCount = context.state.retryCount ?? 0;

      // Prevent excessive calculations with large attempt counts
      const safeCount = Math.min(retryCount, MAX_SAFE_RETRY_COUNT);

      // Calculate exponential backoff
      const delay = INITIAL_RETRY_DELAY_MS * Math.pow(RETRY_BACKOFF_FACTOR, safeCount);

      // Ensure delay doesn't exceed maximum and call the callback with the delay
      cb(null, Math.min(delay, MAX_RETRY_DELAY_MS));
    },
  });

  // Log retry agent configuration
  const loggableOptions = {
    maxRetries: retryOptions.maxRetries ?? DEFAULT_MAX_RETRIES,
    statusCodes: retryOptions.statusCodes ?? [...DEFAULT_RETRY_STATUS_CODES],
    errorCodes: retryOptions.errorCodes ?? [...DEFAULT_RETRY_ERROR_CODES],
    agentOptions: Object.keys(agentOptions).length > 0 ? '[Agent Options Present]' : undefined,
  };

  logger.info(`[RetryAgent] Initialized with options: ${JSON.stringify(loggableOptions)}`);

  return retryAgent;
}

export type { HttpClientOptions, RetryOptions };
